// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Used only by the Prisma CLI (migrate / db push / introspect). Point it
    // at a session or direct connection so DDL and advisory locks work — on
    // Supabase that's the Session pooler (the true Direct connection is
    // IPv6-only and unreachable from Vercel's IPv4 build). The app's runtime
    // connection is separate (lib/prisma.ts, DATABASE_URL), so this can be a
    // different URL. Falls back to DATABASE_URL for local dev, where one
    // database serves both.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
